### ISSUE TITLE
Cannot successfully share Calendar with Everyone-Group 0.1.0 in NC 14/15/16

### ISSUE THREAD

**Issue by fwolfst** [icewind1991/group_everyone#1]
Thanks for the plugin. Needed functionality.
In NC 14.0.0 with plugin version 0.1.0 I cannot share a Calender with the everyone-group (files/folders do work). The log has this entry which I believe is connected:

```
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing
'SELECT `uid`, `displayname` FROM `oc_users` `u`
  LEFT JOIN `oc_preferences` `p` ON (`userid` = `uid`)
    AND (`appid` = 'settings') AND (`configkey` = 'email')
  WHERE (`uid` COLLATE UTF8_general_ci LIKE ?) OR (`displayname` COLLATE UTF8_general_ci LIKE ?) OR (`configvalue` COLLATE UTF8_general_ci LIKE ?)
  ORDER BY `uid_lower` ASC LIMIT -1 OFFSET 0' with params ["%%", "%%", "%%"]: 

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; 
check the manual that corresponds to your MariaDB server version for the right syntax to use
near '-1 OFFSET 0' at line 1
```
(new-lines and some spaces inserted for readability)

Most users are authenticated via LDAP in my setup.
In the calendar-app, the everyone-group autocompletes and is selectable, but afterwards the entry does not show up in the list of share-receivers (under the calendar name).

**Comment by fwolfst** [comment]
Okay, either I found the problem, or a workaround for my setup ;)

**Comment by fwolfst** [comment]
The error persists in NC 15.0.5 and group_everyone 0.1.1 .
Same error messages, fixed by same commit. Might just be a feeling, but it also makes editing a calender shared with a 100+member group significantly faster.

**Comment by rollanders** [comment]
This error still remains - NC 16.01, Everyone Group 0.1.2
I have not tried the fix. It is not sufficiently clearly described. I assume some changes needs to be done in the app - not needing a fix.

**Comment by tikoflano** [comment]
So what was the fix? I'm having problems with this too

**Comment by fwolfst** [comment]
@rollanders: I updated the pull request. Basically you add two lines of code in `apps/group_everyone`.

**Comment by fwolfst** [comment]
> I assume some changes needs to be done in the app - not needing a fix.

That is what I call a **fix** (changing the code such that it works better) :)
