### ISSUE TITLE
New users can't see folders shared with Everyone

### ISSUE THREAD

**Issue by BastianMuc** [icewind1991/group_everyone#16]
Hi,

using NC 18.0.1, I installed the Everyone plugin, created a few folders and shared them with the Everyone group.

I then created a number of additional users.

Those new users (who automatically gor assigned to Everyone) though weren't able to see the folders previously shared. Only after I had removed the sharing from the folders and shared with Everyone again, the new users gained access.

From my point of view, new users should immediately have access to all content previously shared with "Everyone".

Thanks,
Bastian

**Comment by JeanLafon** [comment]
Bonjour à tous.
Nous avons le même problème. Le groupe virtuel "Tout le monde" ne comprend pas toujours tous les utilisateurs !?
Merci de regarder.
Jean

Good morning all.
We have the same problem. The "Everyone" virtual group does not always include all users !?
Thanks for watching.
Jean

**Comment by jo23sh** [comment]
I had the same issue. To solve this, I have just submitted a new app called [Auto Groups](https://apps.nextcloud.com/apps/auto_groups) to the NC app store.

In contrast to `group_everyone`, which basically creates a virtual Group Backend reporting back all users, [Auto Groups](https://apps.nextcloud.com/apps/auto_groups) adds users to one or multiple _real_ groups in your existing, normal Group Backend. Additionally, one or multiple "override groups" can be defined to exclude specific accounts from the Auto Groups (e.g., for Service Accounts).

The source is here: https://github.com/stjosh/auto_groups . I would be happy if it is useful to others as well... 😃

**Comment by icewind1991** [comment]
should be fixed with 0.1.5
