### ISSUE TITLE
Add support for NC 23

### ISSUE THREAD

**Issue by jurgenhaas** [icewind1991/group_everyone#23]
The app store at https://apps.nextcloud.com/apps/group_everyone doesn't show support for NC 23 yet, are you planning to support that platform?

**Comment by fschrempf** [comment]
Looks like support was added (https://github.com/icewind1991/group_everyone/commit/afa40f2b718c53287759c19094d4a83db680fbf6), but not yet released.

**Comment by tj775** [comment]
A brief statement about the status would be helpful. Will NC23 be supported? Is there a timeline? Thanks!

**Comment by afics** [comment]
Hey @icewind1991, 

please tag 0.1.9 :)

**Comment by icewind1991** [comment]
Sorry for the delays

**Comment by tj775** [comment]
Thanx!
