### ISSUE TITLE
CHANGELOG.md is not up-to-date with releases

### ISSUE THREAD

**Issue by SimJoSt** [icewind1991/group_everyone#24]
The https://github.com/icewind1991/group_everyone/blob/master/CHANGELOG.md file is not up-to-date with the newest releases from https://github.com/icewind1991/group_everyone/releases  
And that's excluding the releases made on the Nextcloud version specific branches.

Thanks for the continued work 🙏

**Comment by bthall** [comment]
Confirmed the same. Currently holding on applying an update due to missing changelog.

**Comment by SimJoSt** [comment]
And it also doesn't adhere to:
- https://nextcloudappstore.readthedocs.io/en/latest/developer.html?highlight=changelog#changelog
- https://keepachangelog.com/

So the "Changelog" tab in the Nextcloud admin app interface stays empty when opening the details of the app.

**Comment by SimJoSt** [comment]
I also saw, that 0.1.13 is not marked as the "latest" release: https://github.com/icewind1991/group_everyone/releases/latest
