### ISSUE TITLE
Internal server error for Group admin

### ISSUE THREAD

**Issue by wiswedel** [icewind1991/group_everyone#8]
Promoting a user as group admin for the Everyone group results in an internal server error when that user opens the user admin page.
Doesn't matter if the user is group admin only for Everyone or also for other groups.

These are the logs:

[index] Error: Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'SELECT `uid`, `displayname` FROM `oc_users` `u` LEFT JOIN `oc_preferences` `p` ON (`userid` = `uid`) AND (`appid` = 'settings') AND (`configkey` = 'email') WHERE (`uid`  COLLATE utf8mb4_general_ci LIKE ?) OR (`displayname`  COLLATE utf8mb4_general_ci LIKE ?) OR (`configvalue`  COLLATE utf8mb4_general_ci LIKE ?) ORDER BY `uid_lower` ASC LIMIT -1 OFFSET 0' with params ["%%", "%%", "%%"]:

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-1 OFFSET 0' at line 1 at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 128
    convertException("An exception oc ... 1", Doctrine\DBAL\Dr ... ]})
 1. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 855
    driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "SELECT `uid`, ` ... 0", {1: "%%",2: "%%",3: "%%"})
 2. /var/www/nextcloud/lib/private/DB/Connection.php line 195
    executeQuery("SELECT `uid`, ` ... 0", {1: "%%",2: "%%",3: "%%"}, {1: 2,2: 2,3: 2}, null)
 3. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 206
    executeQuery("SELECT `uid`, ` ... 0", {1: "%%",2: "%%",3: "%%"}, {1: 2,2: 2,3: 2})
 4. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 214
    execute()
 5. /var/www/nextcloud/lib/private/User/Database.php line 282
    execute()
 6. /var/www/nextcloud/lib/private/User/Database.php line 383
    getDisplayNames("", -1, 0)
 7. /var/www/nextcloud/lib/private/User/Manager.php line 229
    getUsers("", -1, 0)
 8. /opt/ncApps/group_everyone/lib/GroupBackend.php line 77
    search("", -1, 0)
 9. /var/www/nextcloud/lib/private/Group/Group.php line 111
    usersInGroup("everyone")
10. /var/www/nextcloud/lib/private/User/Manager.php line 400
    getUsers()
11. /var/www/nextcloud/settings/Controller/UsersController.php line 212
    countUsersOfGroups({everyone: OC\Group\Group {}})
12. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    usersList()
13. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OC\Settings\Controller\UsersController {}, "usersList")
14. /var/www/nextcloud/lib/private/AppFramework/App.php line 118
    dispatch(OC\Settings\Controller\UsersController {}, "usersList")
15. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("OC\\Settings\\C ... r", "usersList", OC\AppFramework\ ... {}, {_route: "settings.Users.usersList"})
16. <<closure>>
    __invoke({_route: "settings.Users.usersList"})
17. /var/www/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "settings.Users.usersList"})
18. /var/www/nextcloud/lib/base.php line 987
    match("/settings/users")
19. /var/www/nextcloud/index.php line 42
    handleRequest()

GET /index.php/settings/users
from 192.168.56.1 by testUser at 2019-02-14T09:11:51+00:00

App version 0.1.1
NC version 15.0.4

**Comment by icewind1991** [comment]
same underlying issue as #1
